# Example configuration file for the CLI application
# Copy this file to ~/.config/cli-app/config.toml and modify as needed

# API Configuration
api_endpoint = "https://api.example.com"
api_token = "your-api-token-here"

# Request Configuration
timeout = 30
verify_ssl = true

# Logging Configuration
log_level = "INFO"

# Additional Configuration
# You can also set these via environment variables:
# CLI_APP_API_ENDPOINT, CLI_APP_API_TOKEN, CLI_APP_TIMEOUT, etc.

# Or override them via command line:
# cli-app --endpoint https://custom.api.com --timeout 60